use_frameworks!

platform :ios, '8.0'

target 'LWAspectsHook_Example' do
  pod 'LWAspectsHook', :path => '../'

  pod 'Aspects'

  # target 'LWAspectsHook_Tests' do
  #   inherit! :search_paths
  # end
end
